export const GET_URHEILIJATIEDOT = "GET_URHEILIJATIEDOT";
export const GET_URHEILIJATIETO = "GET_URHEILIJATIETO";
export const DELETE_URHEILIJATIETO = "DELETE_URHEILIJATIETO";
export const ADD_URHEILIJATIETO = "ADD_URHEILIJATIETO";